# Generated by Django 3.2.11 on 2022-02-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField()),
                ('employee_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('designation', models.CharField(max_length=100)),
                ('department', models.IntegerField()),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('bank_account_number', models.BigIntegerField()),
                ('working_days', models.IntegerField()),
                ('no_of_leaves', models.IntegerField()),
                ('provident_fund_number', models.IntegerField()),
                ('fixed_annual_ctc', models.IntegerField()),
                ('monthly_ctc', models.IntegerField()),
                ('balance_leaves', models.IntegerField()),
            ],
        ),
    ]
